### ISSUE TITLE
How to load local pre-trained parameters?

### ISSUE THREAD

**Issue by S1Y1B** [moment-timeseries-foundation-model/moment-research#14]
Hello, author. Could you please explain how to load your own pre-trained model? It seems that you haven't mentioned this issue in the code.

**Comment by S1Y1B** [comment]
Running the code provided by the author:
python scripts/finetuning/forecasting.py \
  --finetuning_mode 'linear-probing' \
  --config 'configs/forecasting/linear_probing.yaml' \
  --gpu_id 0 \
  --forecast_horizon 96 \
  --init_lr 0.0001 \
  --dataset_names '/TimeseriesDatasets/forecasting/autoformer/ETTh1.csv'

Results in an immediate error:
Loading train split of the dataset
Traceback (most recent call last):
  File "/moment-research-main/scripts/finetuning/forecasting.py", line 109, in <module>
    forecasting(
  File "/moment-research-main/scripts/finetuning/forecasting.py", line 59, in forecasting
    task_obj = ForecastFinetuning(args=args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moment-research-main/moment/tasks/forecast_finetune.py", line 27, in __init__
    super().__init__(args=args, **kwargs)
  File "/moment-research-main/moment/tasks/base.py", line 41, in __init__
    self.train_dataloader = self._get_dataloader(data_split="train")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moment-research-main/moment/tasks/base.py", line 94, in _get_dataloader
    self._dataloader[data_split] = get_timeseries_dataloader(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moment-research-main/moment/data/dataloader.py", line 128, in get_timeseries_dataloader
    dataset = dataset_name_to_class[args.dataset_names](**vars(args))
              ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '/TimeseriesDatasets/forecasting/autoformer/ETTh1.csv'
What’s the issue here?
